config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get 'users/show', to: 'users/registrations#show'
  end
    devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords', registrations: 'users/registrations' }

  post 'user_token' => 'user_token#create'
  get 'pharmacies/all(:id)',   to: 'pharmacies#all'
  resources :pharmacies
  resources :regions
  resources :pharmacy_webs

  get 'percentages/new_w_pharm/(:id)', to: 'percentages#newex', as: 'create_new_for_pharm'
  resources :percentages

 # resources :groups
 root "getinvoice#index"
 # devise_for :users
#  resources :products
  post 'reg_json', to: 'regions#showalljson'
  get 'products/all', to: 'products#index'
  post 'products/searching', to: 'products#searching'
  post 'products/detailproduct', to: 'products#dtlprod'
  post 'products',      to: 'products#showproductsfromgroup'
  resources :products
  get 'groups/all',   to: 'groups#all'
  get 'groups/alln',   to: 'groups#alln'
  get 'groups/:id',        to: 'groups#showgrp'

#  get 'pharmacies/all(:id)',   to: 'pharmacies#all'

  get 'prod_exp/all',   to: 'special_offer#getSpecialOffer'
  post 'offers',to: 'special_offer#getOffersFromApt'

#  post 'makeinv/:invoice',   to: 'makeinv#all'
  post 'makeinv',   to: 'makeinv#all'
  post 'get_invoice_api',        to: 'get_invoice_api#showinv'
  post 'get_invoice_api/detail',        to: 'get_invoice_api#showdetailinvoice'
  #site
   get  'getinvoice/(:fltr)/showall', to: 'getinvoice#index' , as: :invoice
   get  'getinvoice/:id/edit', to: 'getinvoice#edit', as: :edit_invoice
   post  'getinvoice/change/:id', to: 'getinvoice#change'
  #resources :getinvoice

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/details_invoice.rb
class DetailsInvoice < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  has_and_belongs_to_many :products
end

app/models/invoice.rb
class Invoice < ApplicationRecord
    has_many:items
    belongs_to :pharmacy
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/percentage.rb
class Percentage < ApplicationRecord
   belongs_to :pharmacy
end

app/models/pharmacy.rb
class Pharmacy < ApplicationRecord
  has_many :prices, :class_name => 'Price'
  has_many :products, through: :prices
  belongs_to :pharmacy_web, :class_name => 'PharmacyWeb'
  belongs_to :region
  belongs_to :user
end

app/models/pharmacy_web.rb
class PharmacyWeb < ApplicationRecord
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :product
  belongs_to :pharmacy
end

app/models/price_ava.rb
class PriceAva < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many :groups
  has_many :prices, :class_name => 'Price'
  has_many :pharmacies, through: :prices
end

app/models/reference.rb
class Reference < ApplicationRecord
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/rl.rb
class Rl < ApplicationRecord
end

app/models/special_offer.rb
class SpecialOffer < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    #belongs_to :invoice


  alias_method :authenticate, :valid_password?

def self.from_token_payload(payload)
  self.find payload["sub"]
end

end

app/controllers/pharmacy_webs_controller.rb
class PharmacyWebsController < ApplicationController
  before_action :set_pharmacy_web, only: [:show, :edit, :update, :destroy]

  # GET /pharmacy_webs
  # GET /pharmacy_webs.json
  def index
    @pharmacy_webs = PharmacyWeb.all
  end

  # GET /pharmacy_webs/1
  # GET /pharmacy_webs/1.json
  def show
  end

  # GET /pharmacy_webs/new
  def new
    @pharmacy_web = PharmacyWeb.new
  end

  # GET /pharmacy_webs/1/edit
  def edit
  end

  # POST /pharmacy_webs
  # POST /pharmacy_webs.json
  def create
    @pharmacy_web = PharmacyWeb.new(pharmacy_web_params)

    respond_to do |format|
      if @pharmacy_web.save
        format.html { redirect_to @pharmacy_web, notice: 'Pharmacy web was successfully created.' }
        format.json { render :show, status: :created, location: @pharmacy_web }
      else
        format.html { render :new }
        format.json { render json: @pharmacy_web.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pharmacy_webs/1
  # PATCH/PUT /pharmacy_webs/1.json
  def update
    respond_to do |format|
      if @pharmacy_web.update(pharmacy_web_params)
        format.html { redirect_to @pharmacy_web, notice: 'Pharmacy web was successfully updated.' }
        format.json { render :show, status: :ok, location: @pharmacy_web }
      else
        format.html { render :edit }
        format.json { render json: @pharmacy_web.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pharmacy_webs/1
  # DELETE /pharmacy_webs/1.json
  def destroy
    @pharmacy_web.destroy
    respond_to do |format|
      format.html { redirect_to pharmacy_webs_url, notice: 'Pharmacy web was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pharmacy_web
      @pharmacy_web = PharmacyWeb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pharmacy_web_params
      params.require(:pharmacy_web).permit(:name, :director, :phone, :addres)
    end
end

app/helpers/makeinv_helper.rb
module MakeinvHelper
end

app/helpers/pharmacies_helper.rb
module PharmaciesHelper
  def getPharmacies
    widgets = DBF::Table.new("Pharmacies.dbf", nil, 'cp866')
    widgets.each do |record|
      if Pharmacy.where(:id => record.id).exists?
        @p=Pharmacy.find_by_id(record.id)
        @p.name = record.name
        @p.phone = record.phone
        @p.adress = record.adress
        @p.description = record.descriptio
        @p.pharmacy_web_id = record.web
        @p.region_id = record.reg
        @p.save
        puts record.name
      else
        @p=Pharmacy.new
        @p.id = record.id
        @p.name = record.name
        @p.phone = record.phone
        @p.adress = record.adress
        @p.description = record.descriptio
        @p.pharmacy_web_id = record.web
        @p.region_id = record.reg
        @p.save
        puts record.phone
      end
    end
  end

def uppharm
#  @p = Pharmacy.all
#  @p.each do |pharm|
#    pharm.timeopen = "8.00 - 10.00"
#    pharm.save
#  end
end
end

app/helpers/pharmacy_webs_helper.rb
module PharmacyWebsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/pharmacy_webs/_form.html.erb
<%= form_for(pharmacy_web) do |f| %>
  <% if pharmacy_web.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pharmacy_web.errors.count, "error") %> prohibited this pharmacy_web from being saved:</h2>

      <ul>
      <% pharmacy_web.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :director %>
    <%= f.text_field :director %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :addres %>
    <%= f.text_field :addres %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pharmacy_webs/edit.html.erb
<h1>Editing Pharmacy Web</h1>

<%= render 'form', pharmacy_web: @pharmacy_web %>

<%= link_to 'Show', @pharmacy_web %> |
<%= link_to 'Back', pharmacy_webs_path %>

app/views/pharmacy_webs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pharmacy Webs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Director</th>
      <th>Phone</th>
      <th>Addres</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pharmacy_webs.each do |pharmacy_web| %>
      <tr>
        <td><%= pharmacy_web.name %></td>
        <td><%= pharmacy_web.director %></td>
        <td><%= pharmacy_web.phone %></td>
        <td><%= pharmacy_web.addres %></td>
        <td><%= link_to 'Show', pharmacy_web %></td>
        <td><%= link_to 'Edit', edit_pharmacy_web_path(pharmacy_web) %></td>
        <td><%= link_to 'Destroy', pharmacy_web, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pharmacy Web', new_pharmacy_web_path %>

app/views/pharmacy_webs/new.html.erb
<h1>New Pharmacy Web</h1>

<%= render 'form', pharmacy_web: @pharmacy_web %>

<%= link_to 'Back', pharmacy_webs_path %>

app/views/pharmacy_webs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pharmacy_web.name %>
</p>

<p>
  <strong>Director:</strong>
  <%= @pharmacy_web.director %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @pharmacy_web.phone %>
</p>

<p>
  <strong>Addres:</strong>
  <%= @pharmacy_web.addres %>
</p>

<%= link_to 'Edit', edit_pharmacy_web_path(@pharmacy_web) %> |
<%= link_to 'Back', pharmacy_webs_path %>