config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get 'users/show', to: 'users/registrations#show'
  end
    devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords', registrations: 'users/registrations' }

  post 'user_token' => 'user_token#create'
  get 'pharmacies/all(:id)',   to: 'pharmacies#all'
  resources :pharmacies
  resources :regions
  resources :pharmacy_webs

  get 'percentages/new_w_pharm/(:id)', to: 'percentages#newex', as: 'create_new_for_pharm'
  resources :percentages

 # resources :groups
 root "getinvoice#index"
 # devise_for :users
#  resources :products
  post 'reg_json', to: 'regions#showalljson'
  get 'products/all', to: 'products#index'
  post 'products/searching', to: 'products#searching'
  post 'products/detailproduct', to: 'products#dtlprod'
  post 'products',      to: 'products#showproductsfromgroup'
  resources :products
  get 'groups/all',   to: 'groups#all'
  get 'groups/alln',   to: 'groups#alln'
  get 'groups/:id',        to: 'groups#showgrp'

#  get 'pharmacies/all(:id)',   to: 'pharmacies#all'

  get 'prod_exp/all',   to: 'special_offer#getSpecialOffer'
  post 'offers',to: 'special_offer#getOffersFromApt'

#  post 'makeinv/:invoice',   to: 'makeinv#all'
  post 'makeinv',   to: 'makeinv#all'
  post 'get_invoice_api',        to: 'get_invoice_api#showinv'
  post 'get_invoice_api/detail',        to: 'get_invoice_api#showdetailinvoice'
  #site
   get  'getinvoice/(:fltr)/showall', to: 'getinvoice#index' , as: :invoice
   get  'getinvoice/:id/edit', to: 'getinvoice#edit', as: :edit_invoice
   post  'getinvoice/change/:id', to: 'getinvoice#change'
  #resources :getinvoice

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/details_invoice.rb
class DetailsInvoice < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  has_and_belongs_to_many :products
end

app/models/invoice.rb
class Invoice < ApplicationRecord
    has_many:items
    belongs_to :pharmacy
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/percentage.rb
class Percentage < ApplicationRecord
   belongs_to :pharmacy
end

app/models/pharmacy.rb
class Pharmacy < ApplicationRecord
  has_many :prices, :class_name => 'Price'
  has_many :products, through: :prices
  belongs_to :pharmacy_web, :class_name => 'PharmacyWeb'
  belongs_to :region
  belongs_to :user
end

app/models/pharmacy_web.rb
class PharmacyWeb < ApplicationRecord
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :product
  belongs_to :pharmacy
end

app/models/price_ava.rb
class PriceAva < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many :groups
  has_many :prices, :class_name => 'Price'
  has_many :pharmacies, through: :prices
end

app/models/reference.rb
class Reference < ApplicationRecord
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/rl.rb
class Rl < ApplicationRecord
end

app/models/special_offer.rb
class SpecialOffer < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    #belongs_to :invoice


  alias_method :authenticate, :valid_password?

def self.from_token_payload(payload)
  self.find payload["sub"]
end

end

app/controllers/percentages_controller.rb
class PercentagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_percentage, only: [:show, :edit, :update, :destroy]

  # GET /percentages
  # GET /percentages.json
  def index
    @percentages = Percentage.all.order("group_id,val_fact_1,val_inv_1")
  end

  # GET /percentages/1
  # GET /percentages/1.json
  def show
  end

  # GET /percentages/new
  def new
    @percentage = Percentage.new
  end

  def newex
    @p = params[:id]
    puts @p
    @percentage = Percentage.new
    @percentage.pharmacy_id = @p
    render 'new'
  end

  # GET /percentages/1/edit
  def edit
  end

  # POST /percentages
  # POST /percentages.json
  def create
    @percentage = Percentage.new(percentage_params)

    respond_to do |format|
      if @percentage.save
        format.html { redirect_to @percentage, notice: 'Percentage was successfully created.' }
        format.json { render :show, status: :created, location: @percentage }
      else
        format.html { render :new }
        format.json { render json: @percentage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /percentages/1
  # PATCH/PUT /percentages/1.json
  def update
    respond_to do |format|
      if @percentage.update(percentage_params)
        format.html { redirect_to @percentage, notice: 'Percentage was successfully updated.' }
        format.json { render :show, status: :ok, location: @percentage }
      else
        format.html { render :edit }
        format.json { render json: @percentage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /percentages/1
  # DELETE /percentages/1.json
  def destroy
    @percentage.destroy
    respond_to do |format|
      format.html { redirect_to percentages_url, notice: 'Percentage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_percentage
      @percentage = Percentage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def percentage_params
      params.require(:percentage).permit(:val_fact_1, :val_fact_2, :percent_fact, :val_inv_1, :val_inv_2, :percent_inv, :group_id, :pharmacy_id)
    end
end

app/helpers/makeinv_helper.rb
module MakeinvHelper
end

app/helpers/percentages_helper.rb
module PercentagesHelper
end

app/helpers/pharmacies_helper.rb
module PharmaciesHelper
  def getPharmacies
    widgets = DBF::Table.new("Pharmacies.dbf", nil, 'cp866')
    widgets.each do |record|
      if Pharmacy.where(:id => record.id).exists?
        @p=Pharmacy.find_by_id(record.id)
        @p.name = record.name
        @p.phone = record.phone
        @p.adress = record.adress
        @p.description = record.descriptio
        @p.pharmacy_web_id = record.web
        @p.region_id = record.reg
        @p.save
        puts record.name
      else
        @p=Pharmacy.new
        @p.id = record.id
        @p.name = record.name
        @p.phone = record.phone
        @p.adress = record.adress
        @p.description = record.descriptio
        @p.pharmacy_web_id = record.web
        @p.region_id = record.reg
        @p.save
        puts record.phone
      end
    end
  end

def uppharm
#  @p = Pharmacy.all
#  @p.each do |pharm|
#    pharm.timeopen = "8.00 - 10.00"
#    pharm.save
#  end
end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/percentages/_form.html.erb
<%= bootstrap_form_for(percentage) do |f| %>
  <% if percentage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(percentage.errors.count, "error") %> prohibited this percentage from being saved:</h2>

      <ul>
      <% percentage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group fr_percentage">
    <%= f.text_field :val_fact_1, label:"Диапазон факт от:" %>

    <%= f.text_field :val_fact_2, label:"Диапазон факт до:" %>

    <%= f.text_field :percent_fact, label:"Процент наценки факт" %>

    <%= f.text_field :val_inv_1, label:"Диапазон заказ от:" %>

    <%= f.text_field :val_inv_2, label:"Диапазон заказ до:" %>

    <%= f.text_field :percent_inv, label:"Процент наценки заказ" %>
    <%= f.text_field :pharmacy_id, label:"Идентификатор аптеки" %>
    <%= f.select :group_id, Group.where('kls_parent=1613').order("NAME ASC").collect{ |group| [group.name, group.id] }, {label: "Группа товара"}%>
  </div>

  <div class="actions">
    <%= f.submit "Подтвердить новый диапазон" %>
  </div>
<% end %>

app/views/percentages/_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Диапазоны наценок по группам товара</h1>
<p>Если группа товара не указана, то процент наценки распространяется на все товары и имеет низший приоритет</p>
<p>Как только вы укажите группу товара в диапазон, то приоритет будет выше чем на товары без группы</p>

<table  class="table table-bordered">
  <thead>
    <tr>
      <th>Диапазон факт от:</th>
      <th>Диапазон факт до:</th>
      <th>Процент наценки факт:</th>
      <th>Диапазон факт до:</th>
      <th>Диапазон факт до:</th>
      <th>Процент наценки заказ:</th>
      <th>Группа товара</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @percentages.each do |percentage| %>
      <tr>
        <td><%= percentage.val_fact_1 %></td>
        <td><%= percentage.val_fact_2 %></td>
        <td><%= percentage.percent_fact %></td>
        <td><%= percentage.val_inv_1 %></td>
        <td><%= percentage.val_inv_2 %></td>
        <td><%= percentage.percent_inv %></td>
        <td><%= Group.find_by('id=:p',{p:percentage.group_id}).name %></td>
        <td><%= link_to 'Просмотреть', percentage %></td>
        <td><%= link_to 'Редактировать', edit_percentage_path(percentage) %></td>
        <td><%= link_to 'Удалить', percentage, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%=@pharmacy_id%>
<%= link_to 'Новый диапазон', create_new_for_pharm_path(@pharmacy_id)  %>

app/views/percentages/edit.html.erb
<h1>Редактирование диапазона</h1>

<%= render 'form', percentage: @percentage %>

<%= link_to 'Показать', @percentage %> |
<%= link_to 'Назад', percentages_path %>

app/views/percentages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Диапазоны наценок по группам товара</h1>
<p>Если группа товара не указана, то процент наценки распространяется на все товары и имеет низший приоритет</p>
<p>Как только вы укажите группу товара в диапазон, то приоритет будет выше чем на товары без группы</p>

<table  class="table table-bordered">
  <thead>
    <tr>
      <th>Диапазон факт от:</th>
      <th>Диапазон факт до:</th>
      <th>Процент наценки факт:</th>
      <th>Диапазон факт до:</th>
      <th>Диапазон факт до:</th>
      <th>Процент наценки заказ:</th>
      <th>Группа товара</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @percentages.each do |percentage| %>
      <tr>
        <td><%= percentage.val_fact_1 %></td>
        <td><%= percentage.val_fact_2 %></td>
        <td><%= percentage.percent_fact %></td>
        <td><%= percentage.val_inv_1 %></td>
        <td><%= percentage.val_inv_2 %></td>
        <td><%= percentage.percent_inv %></td>
        <td><%= Group.find_by('id=:p',{p:percentage.group_id).name}) %></td>
        <td><%= link_to 'Просмотреть', percentage %></td>
        <td><%= link_to 'Редактировать', edit_percentage_path(percentage) %></td>
        <td><%= link_to 'Удалить', percentage, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новый диапазон', new_percentage_path %>

app/views/percentages/new.html.erb
<h1>Новый диапазон</h1>
<%= @pharmacy_id%>
<%= render partial: 'form', locals: {percentage: @percentage, pharmacy_id: @pharmacy_id} %>

<%= link_to 'Назад', percentages_path %>

app/views/percentages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Val fact 1:</strong>
  <%= @percentage.val_fact_1 %>
</p>

<p>
  <strong>Val fact 2:</strong>
  <%= @percentage.val_fact_2 %>
</p>

<p>
  <strong>Percent fact:</strong>
  <%= @percentage.percent_fact %>
</p>

<p>
  <strong>Val inv 1:</strong>
  <%= @percentage.val_inv_1 %>
</p>

<p>
  <strong>Val inv 2:</strong>
  <%= @percentage.val_inv_2 %>
</p>

<p>
  <strong>Percent inv:</strong>
  <%= @percentage.percent_inv %>
</p>

<p>
  <strong>Group:</strong>
  <%= @percentage.group_id %>
</p>

<%= link_to 'Edit', edit_percentage_path(@percentage) %> |
<%= link_to 'Back', percentages_path %>