config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get 'users/show', to: 'users/registrations#show'
  end
    devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords', registrations: 'users/registrations' }

  post 'user_token' => 'user_token#create'
  get 'pharmacies/all(:id)',   to: 'pharmacies#all'
  resources :pharmacies
  resources :regions
  resources :pharmacy_webs

  get 'percentages/new_w_pharm/(:id)', to: 'percentages#newex', as: 'create_new_for_pharm'
  resources :percentages

 # resources :groups
 root "getinvoice#index"
 # devise_for :users
#  resources :products
  post 'reg_json', to: 'regions#showalljson'
  get 'products/all', to: 'products#index'
  post 'products/searching', to: 'products#searching'
  post 'products/detailproduct', to: 'products#dtlprod'
  post 'products',      to: 'products#showproductsfromgroup'
  resources :products
  get 'groups/all',   to: 'groups#all'
  get 'groups/alln',   to: 'groups#alln'
  get 'groups/:id',        to: 'groups#showgrp'

#  get 'pharmacies/all(:id)',   to: 'pharmacies#all'

  get 'prod_exp/all',   to: 'special_offer#getSpecialOffer'
  post 'offers',to: 'special_offer#getOffersFromApt'

#  post 'makeinv/:invoice',   to: 'makeinv#all'
  post 'makeinv',   to: 'makeinv#all'
  post 'get_invoice_api',        to: 'get_invoice_api#showinv'
  post 'get_invoice_api/detail',        to: 'get_invoice_api#showdetailinvoice'
  #site
   get  'getinvoice/(:fltr)/showall', to: 'getinvoice#index' , as: :invoice
   get  'getinvoice/:id/edit', to: 'getinvoice#edit', as: :edit_invoice
   post  'getinvoice/change/:id', to: 'getinvoice#change'
  #resources :getinvoice

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/details_invoice.rb
class DetailsInvoice < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  has_and_belongs_to_many :products
end

app/models/invoice.rb
class Invoice < ApplicationRecord
    has_many:items
    belongs_to :pharmacy
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/percentage.rb
class Percentage < ApplicationRecord
   belongs_to :pharmacy
end

app/models/pharmacy.rb
class Pharmacy < ApplicationRecord
  has_many :prices, :class_name => 'Price'
  has_many :products, through: :prices
  belongs_to :pharmacy_web, :class_name => 'PharmacyWeb'
  belongs_to :region
  belongs_to :user
end

app/models/pharmacy_web.rb
class PharmacyWeb < ApplicationRecord
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :product
  belongs_to :pharmacy
end

app/models/price_ava.rb
class PriceAva < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many :groups
  has_many :prices, :class_name => 'Price'
  has_many :pharmacies, through: :prices
end

app/models/reference.rb
class Reference < ApplicationRecord
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/rl.rb
class Rl < ApplicationRecord
end

app/models/special_offer.rb
class SpecialOffer < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    #belongs_to :invoice


  alias_method :authenticate, :valid_password?

def self.from_token_payload(payload)
  self.find payload["sub"]
end

end

app/controllers/pharmacies_controller.rb
class PharmaciesController < ApplicationController
  before_action :set_pharmacy, only: [:show, :edit, :update, :destroy]


  def all
    @pharm = Pharmacy.all
    render json: @pharm
  end

  # GET /@Pharmacys
  # GET /@Pharmacys.json
  def index
    @pharmacies = Pharmacy.all
  end

  # GET /@Pharmacys/1
  # GET /@Pharmacys/1.json
  def show

  end

  # GET /@Pharmacys/new
  def new
    @pharmacy = Pharmacy.new
  end

  # GET /@Pharmacys/1/edit
  def edit
  end

  # POST /@Pharmacys
  # POST /@Pharmacys.json
  def create
    @pharmacy = Pharmacy.new(pharmacy_params)

    respond_to do |format|
      if @pharmacy.save
        format.html { redirect_to @pharmacy, notice: '@Pharmacy was successfully created.' }
        format.json { render :show, status: :created, location: @pharmacy }
      else
        format.html { render :new }
        format.json { render json: @pharmacy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /@Pharmacys/1
  # PATCH/PUT /@Pharmacys/1.json
  def update
    respond_to do |format|
      if @pharmacy.update(pharmacy_params)
        format.html { redirect_to @pharmacy, notice: '@Pharmacy was successfully updated.' }
        format.json { render :show, status: :ok, location: @pharmacies }
      else
        format.html { render :edit }
        format.json { render json: @pharmacy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /@Pharmacys/1
  # DELETE /@Pharmacys/1.json
  def destroy
    @pharmacy.destroy
    respond_to do |format|
      format.html { redirect_to pharmacy_url, notice: 'Pharmacy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pharmacy
      @pharmacy = Pharmacy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pharmacy_params
      params.require(:pharmacy).permit(:name,:region_id,:region,:pharmacy_web_id,:user_id)
    end
#,:timeopen,:pharmcy_web_id,:adress,:description,:status,:phone
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/makeinv_helper.rb
module MakeinvHelper
end

app/helpers/pharmacies_helper.rb
module PharmaciesHelper
  def getPharmacies
    widgets = DBF::Table.new("Pharmacies.dbf", nil, 'cp866')
    widgets.each do |record|
      if Pharmacy.where(:id => record.id).exists?
        @p=Pharmacy.find_by_id(record.id)
        @p.name = record.name
        @p.phone = record.phone
        @p.adress = record.adress
        @p.description = record.descriptio
        @p.pharmacy_web_id = record.web
        @p.region_id = record.reg
        @p.save
        puts record.name
      else
        @p=Pharmacy.new
        @p.id = record.id
        @p.name = record.name
        @p.phone = record.phone
        @p.adress = record.adress
        @p.description = record.descriptio
        @p.pharmacy_web_id = record.web
        @p.region_id = record.reg
        @p.save
        puts record.phone
      end
    end
  end

def uppharm
#  @p = Pharmacy.all
#  @p.each do |pharm|
#    pharm.timeopen = "8.00 - 10.00"
#    pharm.save
#  end
end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/pharmacies/_form.html.erb
<%= bootstrap_form_for(pharmacy) do |f| %>
  <% if pharmacy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pharmacy.errors.count, "error") %> prohibited this pharmacy from being saved:</h2>

      <ul>
      <% pharmacy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, label:"Полное название" %>

    <%= f.select :pharmacy_web_id, PharmacyWeb.all.collect{|p| [p.name,p.id]}, { label: "Аптечная сеть:" } %>
    <%= f.select :user_id, User.all.collect{|p| [p.email,p.id]}, { label: "Пользователь для доступа к заказам (email):" } %>

  </div>

  <%= f.select :region_id, Region.all.collect{|p| [p.name,p.id]}, { label: "Район, в котором находится аптека:" } %>


  <div class="actions">
    <%= f.submit "Обновить" %>
  </div>
<% end %>

app/views/pharmacies/edit.html.erb
<h1>Редактирование данных аптеки</h1>

<%= render 'form', pharmacy: @pharmacy %>

<% @percentages = Percentage.where('pharmacy_id=:p',{p:@pharmacy.id}).order("group_id,val_fact_1,val_inv_1") %>
<% @pharmacy_id = @pharmacy.id%>
<%= render partial: 'percentages/index', locals: {percentages: @percentages,pharmacy_id: @pharmacy_id} %>

<%= link_to 'Show', @pharmacy %> |
<%= link_to 'Back', pharmacies_path %>

app/views/pharmacies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pharmacies</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Сеть</th>
      <th>Название аптеки</th>
      <th>Район</th>
      <th>email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pharmacies.each do |pharmacy| %>
      <tr>
        <td><%= pharmacy.pharmacy_web.name %></td>
        <td><%= pharmacy.name %></td>
        <td><%= pharmacy.region.name %></td>
        <td><%= pharmacy.user.email %></td>
        <td><%= link_to 'Show', pharmacy %></td>
        <td><%= link_to 'Edit', edit_pharmacy_path(pharmacy) %></td>
        <td><%= link_to 'Destroy', pharmacy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pharmacy', new_pharmacy_path %>

app/views/pharmacies/new.html.erb
<h1>New Pharmacy</h1>

<%= render 'form', pharmacy: @pharmacy %>

<%= link_to 'Back', pharmacies_path %>

app/views/pharmacies/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @pharmacy.name %>
</p>
<%= link_to 'Edit', edit_pharmacy_path(@pharmacy) %> |
<%= link_to 'Back', pharmacies_path %>